server:
 port: 8081

spring:
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.mysql.jdbc.Driver
   #useAffectedRows=true 配置这个后返回的是数据受影响的条数, 未配置显示的是匹配的要修改的数据条数
   url: jdbc:mysql://127.0.0.1:3306/dubbo_learn?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&useAffectedRows=true
   username: root
   password: root
   dbcp2:
     min-idle: 5
     initial-size: 5
     max-total: 40
     max-wait-millis: 60000

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: dubbo-provider
  registry:
    address: redis://127.0.0.1:6379
    username: auth
    password: 12345
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry


